#if UNITY_EDITOR
using System.IO;
using FlowIoC.BaseModule.ProjectPaths;
using FlowIoC.Editor.AgentRules;
using UnityEngine;

namespace FlowIoC.Editor.Modules
{
    /// <summary>
    /// Keeps a `.gitignore` beside `FlowIoCModuleIndex.asset` so the index stays out of the
    /// consuming project's history. Two people adding modules on separate branches would
    /// otherwise meet in the same serialized asset, and what they would be resolving by hand is
    /// a cache the next rebuild reproduces anyway.
    ///
    /// The rule lives next to the file it governs rather than in the project's root
    /// `.gitignore`: a `.gitignore` only reaches the directory it sits in and below, so a rule in
    /// the package could never reach `Assets/` at all - and FlowIoC owns this folder, while the
    /// root file belongs to the project. It is also the folder the path migrator can move, which
    /// a root-level path would not follow. Unity does not import files whose name starts with a
    /// dot, so this one needs no `.meta` and never appears in the Project window.
    ///
    /// A project that already committed the asset keeps committing it: `.gitignore` does not
    /// untrack what git is already tracking, and `git rm --cached` is the user's call, not this
    /// code's.
    /// </summary>
    internal class ModuleIndexIgnoreRule
    {
        internal const string FileName = ".gitignore";

        /// <summary>
        /// The block's own version, not FlowIoC's. Writing the package version here would rewrite
        /// the file - and show up as a diff in every consuming project - on every upgrade, which
        /// is the churn this whole rule exists to prevent.
        /// </summary>
        private const string RuleVersion = "1";

        private readonly FlowIoCProjectPaths _paths = new FlowIoCProjectPaths();

        internal ManagedBlockStyle Style =>
            new ManagedBlockStyle(
                "# FLOWIOC:BEGIN ",
                string.Empty,
                "# FLOWIOC:END",
                "generated by FlowIoC - do not edit inside this block",
                ".gitignore",
                "reopen the project");

        /// <summary>
        /// The asset and its `.meta`, by name rather than by path, because the rule is read
        /// relative to the file it is written into.
        /// </summary>
        internal string Body()
        {
            string indexFileName = Path.GetFileName(_paths.ModuleIndex);
            return indexFileName + "\n" + indexFileName + ".meta";
        }

        /// <summary>
        /// Writes the block, leaving anything else in the file alone. Does nothing when the
        /// folder does not exist yet - the caller creates it before the index asset lands in it.
        /// </summary>
        internal void Ensure()
        {
            string directory = Path.GetDirectoryName(_paths.ModuleIndex);
            if (string.IsNullOrEmpty(directory) || !Directory.Exists(directory)) return;

            string path = Path.Combine(directory, FileName);
            string existing = File.Exists(path) ? File.ReadAllText(path) : string.Empty;

            BlockWriteResult result = new ManagedBlockWriter(Style).Write(existing, Body(), RuleVersion);

            switch (result.Status)
            {
                case BlockWriteStatus.Unchanged:
                    return;

                case BlockWriteStatus.Refused:
                    Debug.LogWarning($"<color=cyan>FlowIoC:</color> {result.Message}");
                    return;

                default:
                    File.WriteAllText(path, result.Text);
                    return;
            }
        }
    }
}

#endif
