#if UNITY_EDITOR

using FlowIoC.Editor.AgentRules;

namespace FlowIoC.Editor.ModuleCards
{
    /// <summary>
    /// The generated half of a card, written the way the rule block in AGENTS.md is written.
    /// Everything destructive is already handled by ManagedBlockWriter: a card whose markers a
    /// reader has broken is refused rather than rewritten, and the authored half above the block
    /// is never touched.
    /// </summary>
    internal class ModuleCardWriter
    {
        /// <summary>
        /// The block format's own version, deliberately not FlowIoC's. Cards are committed, so
        /// stamping the package version here would rewrite every card in every consuming project
        /// on every upgrade - the churn ModuleIndexIgnoreRule already exists to avoid.
        /// </summary>
        internal const string BLOCK_VERSION = "1";

        internal static ManagedBlockStyle Style =>
            new ManagedBlockStyle(
                "<!-- FLOWIOC:BEGIN ",
                " -->",
                "<!-- FLOWIOC:END -->",
                "generated by Tools/FlowIoC/Module Scanner - do not edit inside this block",
                ModuleCardFile.FILE_NAME,
                "run Module Scanner again");

        private readonly ManagedBlockWriter _writer = new ManagedBlockWriter(Style);

        internal BlockWriteResult Write(string existingCard, string blockBody) =>
            _writer.Write(existingCard, blockBody, BLOCK_VERSION);

        /// <summary>
        /// Whether writing the block would change the card. This asks the writer rather than
        /// comparing hashes, because the hash only describes what the block was rendered from: a
        /// reader who edited inside the block leaves the hash line intact and would otherwise go
        /// undetected. Refused is not stale - a card whose markers are broken is a different
        /// report, and the caller makes it.
        /// </summary>
        internal bool IsStale(string existingCard, string blockBody)
        {
            BlockWriteStatus status = Write(existingCard, blockBody).Status;

            return status == BlockWriteStatus.Created || status == BlockWriteStatus.Updated;
        }
    }
}

#endif