#if UNITY_EDITOR

using System;
using FlowIoC.Editor.AgentRules;

namespace FlowIoC.Editor.ModuleCards
{
    /// <summary>
    /// Keeps MODULES.md out of the project's history. It is derived from the cards, it is
    /// rewritten after every compile, and two people adding modules on separate branches would
    /// otherwise meet in the same generated list - which is the reasoning ModuleIndexIgnoreRule
    /// already applies to ED_ModuleIndex.asset.
    ///
    /// The rule sits beside the file it governs, in Assets/Plugins/FlowIoC, and never in the
    /// consuming project's root .gitignore. A .gitignore changes what somebody's repository
    /// tracks, which is a decision about their history rather than about their code, and FlowIoC
    /// has no business making it for them outside its own folder. ModuleIndexIgnoreRule says the
    /// same thing about ED_ModuleIndex.asset.
    ///
    /// A project that already committed MODULES.md keeps committing it: .gitignore does not
    /// untrack what git is already tracking, and git rm --cached is the user's call.
    /// </summary>
    internal class ModuleDirectoryIgnoreRule
    {
        /// <summary>
        /// The block's own version, not FlowIoC's, so that upgrading the package does not show up
        /// as a diff in every consuming project's .gitignore.
        /// </summary>
        internal const string RULE_VERSION = "1";

        internal static ManagedBlockStyle Style =>
            new ManagedBlockStyle(
                "# FLOWIOC:BEGIN ",
                string.Empty,
                "# FLOWIOC:END",
                "generated by FlowIoC - do not edit inside this block",
                ".gitignore",
                "reopen the project");

        private readonly ManagedBlockWriter _writer = new ManagedBlockWriter(Style);

        /// <summary>
        /// The file and its .meta, by name rather than by path, because the rule is read relative
        /// to the folder it is written into. Unity imports anything under Assets, so the meta has
        /// to go with it or git would track a meta for a file that is not there.
        /// </summary>
        internal string Body() =>
            ModuleDirectoryFile.FILE_NAME + "\n" + ModuleDirectoryFile.FILE_NAME + ".meta";

        internal BlockWriteResult Apply(string existingGitignore) =>
            _writer.Write(existingGitignore, Body(), RULE_VERSION);

        internal bool IsPresent(string existingGitignore)
        {
            string hash = _writer.ReadHash(existingGitignore);

            return hash != null && string.Equals(hash, _writer.ComputeHash(Body()), StringComparison.Ordinal);
        }
    }
}

#endif