#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using FlowIoC.ConsoleModule;
using UnityEditor;
using UnityEngine;

namespace FlowIoC.Editor.Console
{
    internal static class FlowLogTypeGenerator
    {
        private const string GeneratedFolder = "Assets/FlowIoC/Generated";
        private const string GeneratedFilePath = GeneratedFolder + "/FlowLogType.cs";
        private const string AsmRefPath = GeneratedFolder + "/FlowIoC.Generated.asmref";

        private static bool _generatePending;

        [InitializeOnLoadMethod]
        private static void Initialize()
        {
            FlowConsoleSettings.OnProjectLogTypesChanged -= OnProjectLogTypesChanged;
            FlowConsoleSettings.OnProjectLogTypesChanged += OnProjectLogTypesChanged;

            EditorApplication.delayCall += Generate;
        }

        private static void OnProjectLogTypesChanged()
        {
            if (_generatePending) return;
            _generatePending = true;
            EditorApplication.delayCall += () =>
            {
                _generatePending = false;
                Generate();
            };
        }

        public static void Generate()
        {
            var settings = FlowLogger.Settings;
            if (settings == null) return;

            FlowConsoleSettings.FlowConsoleLogType defaultType = null;
            var moduleTypes = new List<FlowConsoleSettings.FlowConsoleLogType>();
            var customTypes = new List<FlowConsoleSettings.FlowConsoleLogType>();

            foreach (var logType in settings.LogTypes)
            {
                if (logType.IsMandatory) continue;

                if (string.Equals(logType.Name, "Default", StringComparison.OrdinalIgnoreCase))
                {
                    defaultType = logType;
                    continue;
                }

                if (logType.IsAutoRegistered)
                    moduleTypes.Add(logType);
                else
                    customTypes.Add(logType);
            }

            if (defaultType == null && moduleTypes.Count == 0 && customTypes.Count == 0)
            {
                CleanupGeneratedFiles();
                return;
            }

            EnsureDirectoryExists();
            EnsureAsmRefExists();

            string content = GenerateClassContent(defaultType, moduleTypes, customTypes);
            string fullPath = GetFullPath(GeneratedFilePath);

            if (File.Exists(fullPath))
            {
                string existing = File.ReadAllText(fullPath);
                if (existing == content)
                {
                    Debug.Log($"<color=cyan>FlowConsole:</color> FlowLogType is already up to date " +
                              $"({moduleTypes.Count} module type(s), {customTypes.Count} custom type(s)).");
                    return;
                }
            }

            File.WriteAllText(fullPath, content);
            AssetDatabase.ImportAsset(GeneratedFilePath, ImportAssetOptions.ForceUpdate);

            Debug.Log($"<color=cyan>FlowConsole:</color> FlowLogType generated with " +
                      $"{moduleTypes.Count} module type(s) and {customTypes.Count} custom type(s).");
        }

        private static string GenerateClassContent(
            FlowConsoleSettings.FlowConsoleLogType defaultType,
            List<FlowConsoleSettings.FlowConsoleLogType> moduleTypes,
            List<FlowConsoleSettings.FlowConsoleLogType> customTypes)
        {
            var sb = new StringBuilder();
            var usedIdentifiers = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by FlowConsole.");
            sb.AppendLine("//     Do not modify. Changes will be overwritten.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("namespace FlowIoC.ConsoleModule");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FlowLogType");
            sb.AppendLine("    {");

            if (defaultType != null)
            {
                string identifier = SanitizeIdentifier(defaultType.Name, usedIdentifiers);
                sb.AppendLine($"        /// <summary>{EscapeXml(defaultType.Name)} (value: {defaultType.Value})</summary>");
                sb.AppendLine($"        public const int {identifier} = {defaultType.Value};");
            }

            if (moduleTypes.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        #region Module Log Types (Auto-Registered)");
                sb.AppendLine();

                foreach (var type in moduleTypes.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
                {
                    string identifier = SanitizeIdentifier(type.Name, usedIdentifiers);
                    sb.AppendLine($"        /// <summary>{EscapeXml(type.Name)} (value: {type.Value})</summary>");
                    sb.AppendLine($"        public const int {identifier} = {type.Value};");
                    sb.AppendLine();
                }

                sb.AppendLine("        #endregion");
            }

            if (customTypes.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        #region Custom Log Types");
                sb.AppendLine();

                foreach (var type in customTypes.OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase))
                {
                    string identifier = SanitizeIdentifier(type.Name, usedIdentifiers);
                    sb.AppendLine($"        /// <summary>{EscapeXml(type.Name)} (value: {type.Value})</summary>");
                    sb.AppendLine($"        public const int {identifier} = {type.Value};");
                    sb.AppendLine();
                }

                sb.AppendLine("        #endregion");
            }

            sb.AppendLine("    }");
            sb.Append("}");

            return sb.ToString();
        }

        internal static string SanitizeIdentifier(string name, HashSet<string> usedIdentifiers)
        {
            if (string.IsNullOrWhiteSpace(name))
                name = "Unknown";

            var sanitized = name.Replace(' ', '_')
                                .Replace('-', '_')
                                .Replace('.', '_');

            sanitized = Regex.Replace(sanitized, @"[^\w]", "");

            if (sanitized.Length == 0)
                sanitized = "Unknown";
            else if (char.IsDigit(sanitized[0]))
                sanitized = "_" + sanitized;

            string original = sanitized;
            int suffix = 1;
            while (!usedIdentifiers.Add(sanitized))
            {
                sanitized = $"{original}_{suffix}";
                suffix++;
            }

            return sanitized;
        }

        private static string EscapeXml(string text)
        {
            return text.Replace("&", "&amp;")
                       .Replace("<", "&lt;")
                       .Replace(">", "&gt;");
        }

        private static void EnsureDirectoryExists()
        {
            string fullPath = GetFullPath(GeneratedFolder);
            if (!Directory.Exists(fullPath))
            {
                Directory.CreateDirectory(fullPath);
                AssetDatabase.ImportAsset(GeneratedFolder, ImportAssetOptions.ForceUpdate);
            }
        }

        private static void EnsureAsmRefExists()
        {
            string fullPath = GetFullPath(AsmRefPath);
            if (File.Exists(fullPath)) return;

            const string asmRefContent = "{\n    \"reference\": \"FlowIoC\"\n}";
            File.WriteAllText(fullPath, asmRefContent);
            AssetDatabase.ImportAsset(AsmRefPath, ImportAssetOptions.ForceUpdate);
        }

        private static void CleanupGeneratedFiles()
        {
            string fullPath = GetFullPath(GeneratedFilePath);
            if (!File.Exists(fullPath)) return;

            AssetDatabase.DeleteAsset(GeneratedFilePath);

            string asmRefFullPath = GetFullPath(AsmRefPath);
            if (File.Exists(asmRefFullPath))
                AssetDatabase.DeleteAsset(AsmRefPath);

            string dirFullPath = GetFullPath(GeneratedFolder);
            if (Directory.Exists(dirFullPath) && Directory.GetFiles(dirFullPath).Length == 0
                                              && Directory.GetDirectories(dirFullPath).Length == 0)
            {
                AssetDatabase.DeleteAsset(GeneratedFolder);
            }
        }

        private static string GetFullPath(string assetPath)
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            return Path.Combine(projectRoot, assetPath);
        }
    }
}
#endif
