#if UNITY_EDITOR

using System;
using System.Text;

namespace FlowIoC.Editor.AgentRules
{
    internal enum BlockWriteStatus
    {
        Created,
        Updated,
        Unchanged,
        Refused,
    }

    internal readonly struct BlockWriteResult
    {
        internal BlockWriteStatus Status { get; }

        /// <summary>The full new file text. On Refused and Unchanged this is the input, unmodified.</summary>
        internal string Text { get; }

        /// <summary>Why the write was refused. Null otherwise.</summary>
        internal string Message { get; }

        internal BlockWriteResult(BlockWriteStatus status, string text, string message = null)
        {
            Status = status;
            Text = text;
            Message = message;
        }
    }

    /// <summary>
    /// Renders and replaces the FlowIoC marker block inside an arbitrary markdown file.
    /// Text in, text out - this type never touches the filesystem, which is what makes
    /// the destructive edge cases (malformed markers, foreign content, line endings)
    /// cheap to test.
    /// </summary>
    internal class ManagedBlockWriter
    {
        private const string BeginPrefix = "<!-- FLOWIOC:BEGIN ";
        private const string EndMarker = "<!-- FLOWIOC:END -->";
        private const string MarkerNote = "generated by Tools/FlowIoC/AI/Agent Rules - do not edit inside this block";

        internal BlockWriteResult Write(string existingText, string blockBody, string version)
        {
            string text = existingText ?? string.Empty;
            string newLine = DetectNewLine(text);
            string block = RenderBlock(blockBody, version, newLine);

            int begin = text.IndexOf(BeginPrefix, StringComparison.Ordinal);
            int end = text.IndexOf(EndMarker, StringComparison.Ordinal);

            if (begin < 0 && end < 0)
                return new BlockWriteResult(BlockWriteStatus.Created, Append(text, block, newLine));

            if (begin < 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    "AGENTS.md contains a FLOWIOC:END marker with no matching FLOWIOC:BEGIN. Fix it by hand and run the sync again.");

            if (end < 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    "AGENTS.md contains a FLOWIOC:BEGIN marker with no matching FLOWIOC:END. Fix it by hand and run the sync again.");

            if (end < begin)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    "AGENTS.md contains a FLOWIOC:END marker before its FLOWIOC:BEGIN. Fix it by hand and run the sync again.");

            if (text.IndexOf(BeginPrefix, begin + BeginPrefix.Length, StringComparison.Ordinal) >= 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    "AGENTS.md contains more than one FLOWIOC block. Remove the extra one by hand and run the sync again.");

            int blockEnd = end + EndMarker.Length;
            string current = text.Substring(begin, blockEnd - begin);

            if (string.Equals(current, block, StringComparison.Ordinal))
                return new BlockWriteResult(BlockWriteStatus.Unchanged, text);

            string updated = text.Substring(0, begin) + block + text.Substring(blockEnd);
            return new BlockWriteResult(BlockWriteStatus.Updated, updated);
        }

        internal string Remove(string existingText)
        {
            string text = existingText ?? string.Empty;

            int begin = text.IndexOf(BeginPrefix, StringComparison.Ordinal);
            int end = text.IndexOf(EndMarker, StringComparison.Ordinal);

            if (begin < 0 || end < begin)
                return text;

            int blockEnd = end + EndMarker.Length;

            while (blockEnd < text.Length && (text[blockEnd] == '\r' || text[blockEnd] == '\n'))
                blockEnd++;

            return text.Substring(0, begin) + text.Substring(blockEnd);
        }

        internal string ReadHash(string existingText)
        {
            string text = existingText ?? string.Empty;

            int begin = text.IndexOf(BeginPrefix, StringComparison.Ordinal);
            if (begin < 0)
                return null;

            const string key = "hash=";
            int hash = text.IndexOf(key, begin, StringComparison.Ordinal);
            if (hash < 0)
                return null;

            int start = hash + key.Length;
            int stop = start;
            while (stop < text.Length && Uri.IsHexDigit(text[stop]))
                stop++;

            return stop > start ? text.Substring(start, stop - start) : null;
        }

        /// <summary>
        /// FNV-1a over the body, rendered as eight hex characters. This detects rule edits
        /// that ship without a version bump; it is a change detector, not a security primitive.
        /// </summary>
        internal string ComputeHash(string blockBody)
        {
            unchecked
            {
                const uint offsetBasis = 2166136261;
                const uint prime = 16777619;

                uint hash = offsetBasis;
                foreach (byte b in Encoding.UTF8.GetBytes(Normalize(blockBody ?? string.Empty)))
                {
                    hash ^= b;
                    hash *= prime;
                }

                return hash.ToString("x8");
            }
        }

        private string RenderBlock(string blockBody, string version, string newLine)
        {
            string body = Normalize(blockBody ?? string.Empty).Replace("\n", newLine);

            var builder = new StringBuilder();
            builder.Append(BeginPrefix)
                .Append("version=").Append(version)
                .Append(" hash=").Append(ComputeHash(blockBody))
                .Append(" | ").Append(MarkerNote).Append(" -->")
                .Append(newLine)
                .Append(body)
                .Append(newLine)
                .Append(EndMarker);

            return builder.ToString();
        }

        private string Append(string text, string block, string newLine)
        {
            if (text.Length == 0)
                return block + newLine;

            string separator = text.EndsWith("\n", StringComparison.Ordinal) ? newLine : newLine + newLine;
            return text + separator + block + newLine;
        }

        /// <summary>The hash must not change when the same rules are written into a CRLF file.</summary>
        private string Normalize(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");

        private string DetectNewLine(string text) =>
            text.IndexOf("\r\n", StringComparison.Ordinal) >= 0 ? "\r\n" : "\n";
    }
}

#endif
