#if UNITY_EDITOR

using System;
using System.Text;

namespace FlowIoC.Editor.AgentRules
{
    internal enum BlockWriteStatus
    {
        Created,
        Updated,
        Unchanged,
        Refused,
    }

    internal readonly struct BlockWriteResult
    {
        internal BlockWriteStatus Status { get; }

        /// <summary>The full new file text. On Refused and Unchanged this is the input, unmodified.</summary>
        internal string Text { get; }

        /// <summary>Why the write was refused. Null otherwise.</summary>
        internal string Message { get; }

        internal BlockWriteResult(BlockWriteStatus status, string text, string message = null)
        {
            Status = status;
            Text = text;
            Message = message;
        }
    }

    /// <summary>
    /// How one managed block is marked out, so the same block logic can manage a markdown file
    /// and a file whose comments start with '#'. <see cref="FileLabel"/> only ever appears in the
    /// message explaining a refusal.
    /// </summary>
    internal readonly struct ManagedBlockStyle
    {
        internal string BeginPrefix { get; }
        internal string BeginSuffix { get; }
        internal string EndMarker { get; }
        internal string MarkerNote { get; }
        internal string FileLabel { get; }

        /// <summary>What a refusal message tells the user to do once they have fixed the markers.</summary>
        internal string Remedy { get; }

        internal ManagedBlockStyle(string beginPrefix, string beginSuffix, string endMarker, string markerNote, string fileLabel, string remedy)
        {
            BeginPrefix = beginPrefix;
            BeginSuffix = beginSuffix;
            EndMarker = endMarker;
            MarkerNote = markerNote;
            FileLabel = fileLabel;
            Remedy = remedy;
        }
    }

    /// <summary>
    /// Renders and replaces the FlowIoC marker block inside an arbitrary text file.
    /// Text in, text out - this type never touches the filesystem, which is what makes
    /// the destructive edge cases (malformed markers, foreign content, line endings)
    /// cheap to test.
    /// </summary>
    internal class ManagedBlockWriter
    {
        private readonly ManagedBlockStyle _style;

        /// <summary>
        /// The markdown block FlowIoC writes into a project's AGENTS.md and CLAUDE.md, which is
        /// what every caller but the module index ignore rule wants.
        /// </summary>
        internal ManagedBlockWriter() : this(new ManagedBlockStyle(
            "<!-- FLOWIOC:BEGIN ",
            " -->",
            "<!-- FLOWIOC:END -->",
            "generated by Tools/FlowIoC/AI/Agent Rules - do not edit inside this block",
            "AGENTS.md",
            "run the sync again"))
        {
        }

        internal ManagedBlockWriter(ManagedBlockStyle style)
        {
            _style = style;
        }

        internal BlockWriteResult Write(string existingText, string blockBody, string version)
        {
            string text = existingText ?? string.Empty;
            string newLine = DetectNewLine(text);
            string block = RenderBlock(blockBody, version, newLine);

            int begin = text.IndexOf(_style.BeginPrefix, StringComparison.Ordinal);
            int end = text.IndexOf(_style.EndMarker, StringComparison.Ordinal);

            if (begin < 0 && end < 0)
                return new BlockWriteResult(BlockWriteStatus.Created, Append(text, block, newLine));

            if (begin < 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    $"{_style.FileLabel} contains a FLOWIOC:END marker with no matching FLOWIOC:BEGIN. Fix it by hand and {_style.Remedy}.");

            if (end < 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    $"{_style.FileLabel} contains a FLOWIOC:BEGIN marker with no matching FLOWIOC:END. Fix it by hand and {_style.Remedy}.");

            if (end < begin)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    $"{_style.FileLabel} contains a FLOWIOC:END marker before its FLOWIOC:BEGIN. Fix it by hand and {_style.Remedy}.");

            if (text.IndexOf(_style.BeginPrefix, begin + _style.BeginPrefix.Length, StringComparison.Ordinal) >= 0)
                return new BlockWriteResult(BlockWriteStatus.Refused, text,
                    $"{_style.FileLabel} contains more than one FLOWIOC block. Remove the extra one by hand and {_style.Remedy}.");

            int blockEnd = end + _style.EndMarker.Length;
            string current = text.Substring(begin, blockEnd - begin);

            if (string.Equals(current, block, StringComparison.Ordinal))
                return new BlockWriteResult(BlockWriteStatus.Unchanged, text);

            string updated = text.Substring(0, begin) + block + text.Substring(blockEnd);
            return new BlockWriteResult(BlockWriteStatus.Updated, updated);
        }

        internal string Remove(string existingText)
        {
            string text = existingText ?? string.Empty;

            int begin = text.IndexOf(_style.BeginPrefix, StringComparison.Ordinal);
            int end = text.IndexOf(_style.EndMarker, StringComparison.Ordinal);

            if (begin < 0 || end < begin)
                return text;

            int blockEnd = end + _style.EndMarker.Length;

            while (blockEnd < text.Length && (text[blockEnd] == '\r' || text[blockEnd] == '\n'))
                blockEnd++;

            return text.Substring(0, begin) + text.Substring(blockEnd);
        }

        internal string ReadHash(string existingText)
        {
            string text = existingText ?? string.Empty;

            int begin = text.IndexOf(_style.BeginPrefix, StringComparison.Ordinal);
            if (begin < 0)
                return null;

            const string key = "hash=";
            int hash = text.IndexOf(key, begin, StringComparison.Ordinal);
            if (hash < 0)
                return null;

            int start = hash + key.Length;
            int stop = start;
            while (stop < text.Length && Uri.IsHexDigit(text[stop]))
                stop++;

            return stop > start ? text.Substring(start, stop - start) : null;
        }

        /// <summary>
        /// FNV-1a over the body, rendered as eight hex characters. This detects rule edits
        /// that ship without a version bump; it is a change detector, not a security primitive.
        /// </summary>
        internal string ComputeHash(string blockBody)
        {
            unchecked
            {
                const uint offsetBasis = 2166136261;
                const uint prime = 16777619;

                uint hash = offsetBasis;
                foreach (byte b in Encoding.UTF8.GetBytes(Normalize(blockBody ?? string.Empty)))
                {
                    hash ^= b;
                    hash *= prime;
                }

                return hash.ToString("x8");
            }
        }

        private string RenderBlock(string blockBody, string version, string newLine)
        {
            string body = Normalize(blockBody ?? string.Empty).Replace("\n", newLine);

            var builder = new StringBuilder();
            builder.Append(_style.BeginPrefix)
                .Append("version=").Append(version)
                .Append(" hash=").Append(ComputeHash(blockBody))
                .Append(" | ").Append(_style.MarkerNote).Append(_style.BeginSuffix)
                .Append(newLine)
                .Append(body)
                .Append(newLine)
                .Append(_style.EndMarker);

            return builder.ToString();
        }

        private string Append(string text, string block, string newLine)
        {
            if (text.Length == 0)
                return block + newLine;

            string separator = text.EndsWith("\n", StringComparison.Ordinal) ? newLine : newLine + newLine;
            return text + separator + block + newLine;
        }

        /// <summary>The hash must not change when the same rules are written into a CRLF file.</summary>
        private string Normalize(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");

        private string DetectNewLine(string text) =>
            text.IndexOf("\r\n", StringComparison.Ordinal) >= 0 ? "\r\n" : "\n";
    }
}

#endif